using System.IO.Compression;
using System.Text;

namespace DefinitionsHelper.Extraction;

/// <summary>
/// Extracts the first-frame PNG image from a .pstr (structure definition) archive.
/// A .pstr file is a gzip-compressed tar archive containing JSON metadata and PNG frame images.
///
/// Uses a lenient tar parser because these files are generated by a JavaScript tar library
/// that produces non-standard numeric fields (null bytes embedded within octal values).
/// </summary>
public static class PstrImageExtractor
{
    private const int TarBlockSize = 512;

    /// <summary>
    /// Extracts the first-frame PNG bytes from raw .pstr file bytes.
    /// Returns null if no PNG frame entry is found.
    /// </summary>
    public static byte[]? Extract(byte[] pstrBytes)
    {
        using var compressedStream = new MemoryStream(pstrBytes);
        using var gzipStream = new GZipStream(compressedStream, CompressionMode.Decompress);
        using var decompressed = new MemoryStream();
        gzipStream.CopyTo(decompressed);
        byte[] data = decompressed.GetBuffer();
        int dataLength = (int)decompressed.Length;

        int offset = 0;
        while (offset + TarBlockSize <= dataLength)
        {
            // End-of-archive: it's a zero block if first byte of header is zero
            if (data[offset] == 0) break;

            string name = ReadNullTerminatedString(data, offset, 100);
            long size = ParseOctalLenient(data, offset + 124, 12);
            byte typeFlag = data[offset + 156];

            offset += TarBlockSize;

            // Verify the claimed size doesn't exceed available data
            if (offset + size > dataLength) break;

            if ((typeFlag == (byte)'0' || typeFlag == 0)
                && name.EndsWith("_1.png", StringComparison.OrdinalIgnoreCase) && size > 0)
            {
                byte[] pngResult = new byte[size];
                Array.Copy(data, offset, pngResult, 0, size);
                return pngResult;
            }

            if (size > 0)
            {
                offset += (int)((size + TarBlockSize - 1) / TarBlockSize * TarBlockSize);
            }
        }

        return null;
    }

    private static string ReadNullTerminatedString(byte[] data, int offset, int maxLength)
    {
        int end = offset + maxLength;
        int nullPos = offset;
        while (nullPos < end && data[nullPos] != 0) nullPos++;
        return Encoding.ASCII.GetString(data, offset, nullPos - offset);
    }

    /// <summary>
    /// Parses an octal number from a tar header field, tolerating embedded null bytes
    /// and non-octal characters after the value (as produced by some JavaScript tar libraries).
    /// </summary>
    private static long ParseOctalLenient(byte[] data, int offset, int length)
    {
        // Read digits up to the first null byte or non-octal character
        long result = 0;
        for (int i = offset; i < offset + length; i++)
        {
            byte b = data[i];
            if (b == 0 || b == (byte)' ') break;
            if (b < (byte)'0' || b > (byte)'7') break;
            result = result * 8 + (b - (byte)'0');
        }
        return result;
    }
}
